name: Backup DB Daily

on:
  schedule:
    - cron: '0 19 * * *' # Cada día a las 19:00 UTC (ajusta zona horaria si quieres)
  workflow_dispatch: # Permite ejecutar manualmente para pruebas

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up PostgreSQL client 17
        run: |
          sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
          wget -qO - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
          sudo apt-get update
          sudo apt-get install -y postgresql-client-17

      - name: Set up Rclone config
        run: |
          mkdir -p ~/.config/rclone
          echo "${{ secrets.RCLONE_CONFIG }}" > ~/.config/rclone/rclone.conf

      - name: Give execute permission to backup script
        run: chmod +x ./backup_db.sh

      - name: Run backup script
        env:
          DB_URL: ${{ secrets.DB_URL }}
          REMOTE_DRIVE: ${{ secrets.RCLONE_REMOTE }}
        run: ./backup_db.sh
