name: Backup DB Daily

on:
  schedule:
    # Se ejecuta cada día a las 19:00 UTC
    - cron: '0 19 * * *'
  workflow_dispatch: # Permite ejecutar manualmente desde GitHub

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up environment
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client
          curl https://rclone.org/install.sh | sudo bash

      - name: Configure rclone
        run: |
          mkdir -p ~/.config/rclone
          echo "${{ secrets.RCLONE_CONF }}" > ~/.config/rclone/rclone.conf

      - name: Make backup executable
        run: chmod +x ./backup_db.sh

      - name: Run backup
        env:
          DB_URL: ${{ secrets.DB_URL }}
        run: ./backup_db.sh
